In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import plotly.graph_objects as go
import datetime
import plotly.express as px
import time
from time import perf_counter
from statistics import mean
import glob
import sys
sys.path.append('C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/notebook/tweet_utils')
import tweets_utils
import importlib
import seaborn as sns
from tqdm.notebook import tqdm
folder = "F:/Supsi/TwitterData/"

In [2]:
repos = []
n_users = []
n_tweets = []
mean = []

In [8]:
repo = glob.glob(folder + "*")
cont = 0
for i in repo[33:]:
#     if cont == 5:
#         break
#     cont = cont + 1
    repos.append(i)
    number_of_tweets = 0
    names = []
    print(i)
    path_profiles = glob.glob(i + "/*users_csv*.csv")
    path_data = glob.glob(i + "/*tweets_csv*.csv")
    users = pd.read_csv(path_profiles[0], lineterminator="\n", low_memory=False)
    tweets = pd.DataFrame()
    for file in path_data:
        for chunk in pd.read_csv(file, lineterminator="\n", low_memory=False, chunksize=int(1e6)):
            names.extend(list(chunk["user_display_name"]))
            number_of_tweets = number_of_tweets + len(chunk)
    median = round(pd.Series(names).value_counts().median(),0)
    print(f"Number of users: {len(users)}")
    n_users.append(len(users))
    print(f"Number of tweets: {number_of_tweets}")
    n_tweets.append(number_of_tweets)
    print(f"Number of tweets per users: {median}")
    mean.append(median)

F:/Supsi/TwitterData\SAz_EG_AE  - 2020
Number of users: 5350
Number of tweets: 36523980
Number of tweets per users: 195.0
F:/Supsi/TwitterData\Serbia - 2020
Number of users: 8558
Number of tweets: 43067074
Number of tweets per users: 1536.0
F:/Supsi/TwitterData\Spain - 2019
Number of users: 259
Number of tweets: 56712
Number of tweets per users: 144.0
F:/Supsi/TwitterData\Tanzania - 2021
Number of users: 268
Number of tweets: 20212
Number of tweets per users: 4.0
F:/Supsi/TwitterData\Thailand - 2020
Number of users: 926
Number of tweets: 21385
Number of tweets per users: 7.0
F:/Supsi/TwitterData\Turkey - 2020
Number of users: 7340
Number of tweets: 36948536
Number of tweets per users: 618.0
F:/Supsi/TwitterData\Uganda - 2021
Number of users: 418
Number of tweets: 524081
Number of tweets per users: 161.0
F:/Supsi/TwitterData\United Arab Emirates - 2019
Number of users: 4248
Number of tweets: 1325530
Number of tweets per users: 186.0
F:/Supsi/TwitterData\United Arab Emirates _Egypt - 2019
Number of users: 271
Number of tweets: 214898
Number of tweets per users: 224.0
F:/Supsi/TwitterData\Venezuela - 2019-1
Number of users: 1196
Number of tweets: 8950562
Number of tweets per users: 453.0
F:/Supsi/TwitterData\Venezuela - 2019-2
Number of users: 755
Number of tweets: 984980
Number of tweets per users: 887.0
F:/Supsi/TwitterData\Venezuela - 2021
Number of users: 277
Number of tweets: 860060
Number of tweets per users: 202.0

In [9]:
df = pd.DataFrame(list(zip(repos, n_users, n_tweets, mean)), 
                       columns = ["Name", "Users number", "Tweets number", "Median"])
df

,Name,Users number,Tweets number,Median
0,F:/Supsi/TwitterData\SAz_EG_AE - 2020,5350,36523980,195.0
1,F:/Supsi/TwitterData\Serbia - 2020,8558,43067074,1536.0
2,F:/Supsi/TwitterData\Spain - 2019,259,56712,144.0
3,F:/Supsi/TwitterData\Tanzania - 2021,268,20212,4.0
4,F:/Supsi/TwitterData\Thailand - 2020,926,21385,7.0
5,F:/Supsi/TwitterData\Turkey - 2020,7340,36948536,618.0
6,F:/Supsi/TwitterData\Uganda - 2021,418,524081,161.0
7,F:/Supsi/TwitterData\United Arab Emirates - 2019,4248,1325530,186.0
8,F:/Supsi/TwitterData\United Arab Emirates _Egy...,271,214898,224.0
9,F:/Supsi/TwitterData\Venezuela - 2019-1,1196,8950562,453.0
10,F:/Supsi/TwitterData\Venezuela - 2019-2,755,984980,887.0
11,F:/Supsi/TwitterData\Venezuela - 2021,277,860060,202.0

In [10]:
df.to_csv("F:/Supsi/TwitterData/data_info_fin.csv", 
          line_terminator="\n", encoding="utf-8", index=False)

In [13]:
path = glob.glob("F:/Supsi/TwitterData/*.csv")
x1 = pd.read_csv(path[0])
x2 = pd.read_csv(path[1])
x3 = pd.read_csv(path[2])
df = x1
df = df.append(x2)
df = df.append(x3)
df = df.reset_index(drop=True)
df

,Name,Users number,Tweets number,Median
0,F:/Supsi/TwitterData\Armenia - 2021,35,72960,36.0
1,F:/Supsi/TwitterData\Catalonia - 2019,129,9489,6.0
2,F:/Supsi/TwitterData\China - 2019 old 1,744,1898108,62.0
3,F:/Supsi/TwitterData\China - 2019 old 2,196,1708078,752.0
4,F:/Supsi/TwitterData\China - 2019 recent,4301,10241545,36.0
5,F:/Supsi/TwitterData\China - 2020,23750,348608,6.0
6,F:/Supsi/TwitterData\China - 2021 Changyu,112,35924,5.0
7,F:/Supsi/TwitterData\China - 2021 Xinjiang,2047,31269,9.0
8,F:/Supsi/TwitterData\Cuba - 2020,526,4802243,2428.0
9,F:/Supsi/TwitterData\Ecuador - 2019,1019,700240,33.0
10,F:/Supsi/TwitterData\Egypt - 2020,2541,7935329,735.0
11,F:/Supsi/TwitterData\Ghana_Nigeria - 2020,70,39964,449.0
12,F:/Supsi/TwitterData\Honduras - 2020,3104,1165019,59.0
13,F:/Supsi/TwitterData\Indonesia - 2020,795,2700296,132.0
14,F:/Supsi/TwitterData\Internet Research Agency ...,3608,8768633,554.0
15,F:/Supsi/TwitterData\Iran - 2018,770,1122936,196.0
16,F:/Supsi/TwitterData\Iran - 2019-1,503,1302012,71.0
17,F:/Supsi/TwitterData\Iran - 2019-2,238,1963141,1136.0
18,F:/Supsi/TwitterData\Iran - 2019-3,2861,254781,22.0
19,F:/Supsi/TwitterData\Iran - 2019-4,2311,4671959,525.0
20,F:/Supsi/TwitterData\Iran - 2020,104,2450,2.0
21,F:/Supsi/TwitterData\Iran - 2021,238,560571,298.0
22,F:/Supsi/TwitterData\Mexico - 2021,276,19277,31.0
23,F:/Supsi/TwitterData\Russia - 2019,416,920761,147.0
24,F:/Supsi/TwitterData\Russia - 2020,1153,3434792,926.0
25,F:/Supsi/TwitterData\Russia - 2021 East Africa,16,7723,21.0
26,F:/Supsi/TwitterData\Russia - 2021 IRA,50,18958,159.0
27,F:/Supsi/TwitterData\Russia GRU - 2021,70,26684,42.0
28,F:/Supsi/TwitterData\Russia IRA - 2021,31,68914,1168.0
29,F:/Supsi/TwitterData\Saudi Arabia - 2019,5929,32054257,232.0
30,F:/Supsi/TwitterData\Saudi Arabia - 2020,33,220254,140.0
31,F:/Supsi/TwitterData\SAz_EG_AE - 2020,5350,36523980,195.0
32,F:/Supsi/TwitterData\Serbia - 2020,8558,43067074,1536.0
33,F:/Supsi/TwitterData\Spain - 2019,259,56712,144.0
34,F:/Supsi/TwitterData\Tanzania - 2021,268,20212,4.0
35,F:/Supsi/TwitterData\Thailand - 2020,926,21385,7.0
36,F:/Supsi/TwitterData\Turkey - 2020,7340,36948536,618.0
37,F:/Supsi/TwitterData\Uganda - 2021,418,524081,161.0
38,F:/Supsi/TwitterData\United Arab Emirates - 2019,4248,1325530,186.0
39,F:/Supsi/TwitterData\United Arab Emirates _Egy...,271,214898,224.0
40,F:/Supsi/TwitterData\Venezuela - 2019-1,1196,8950562,453.0
41,F:/Supsi/TwitterData\Venezuela - 2019-2,755,984980,887.0
42,F:/Supsi/TwitterData\Venezuela - 2021,277,860060,202.0

In [14]:
df.to_csv("F:/Supsi/TwitterData/data_info.csv", 
          line_terminator="\n", encoding="utf-8", index=False)